/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignoutImport } from './routes/signout'
import { Route as NotFoundImport } from './routes/not-found'
import { Route as IndexImport } from './routes/index'
import { Route as SongsIndexImport } from './routes/songs/index'
import { Route as SigninIndexImport } from './routes/signin/index'
import { Route as ReleasesIndexImport } from './routes/releases/index'
import { Route as PlaylistIndexImport } from './routes/playlist/index'
import { Route as ArtistsIndexImport } from './routes/artists/index'
import { Route as AlbumsIndexImport } from './routes/albums/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as AdminAddImport } from './routes/admin/add'
import { Route as AdminEditAlbumIdImport } from './routes/admin/edit/$albumId'

// Create/Update Routes

const SignoutRoute = SignoutImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => rootRoute,
} as any)

const NotFoundRoute = NotFoundImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SongsIndexRoute = SongsIndexImport.update({
  id: '/songs/',
  path: '/songs/',
  getParentRoute: () => rootRoute,
} as any)

const SigninIndexRoute = SigninIndexImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => rootRoute,
} as any)

const ReleasesIndexRoute = ReleasesIndexImport.update({
  id: '/releases/',
  path: '/releases/',
  getParentRoute: () => rootRoute,
} as any)

const PlaylistIndexRoute = PlaylistIndexImport.update({
  id: '/playlist/',
  path: '/playlist/',
  getParentRoute: () => rootRoute,
} as any)

const ArtistsIndexRoute = ArtistsIndexImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => rootRoute,
} as any)

const AlbumsIndexRoute = AlbumsIndexImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const AdminAddRoute = AdminAddImport.update({
  id: '/admin/add',
  path: '/admin/add',
  getParentRoute: () => rootRoute,
} as any)

const AdminEditAlbumIdRoute = AdminEditAlbumIdImport.update({
  id: '/admin/edit/$albumId',
  path: '/admin/edit/$albumId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundImport
      parentRoute: typeof rootRoute
    }
    '/signout': {
      id: '/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof SignoutImport
      parentRoute: typeof rootRoute
    }
    '/admin/add': {
      id: '/admin/add'
      path: '/admin/add'
      fullPath: '/admin/add'
      preLoaderRoute: typeof AdminAddImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
    '/albums/': {
      id: '/albums/'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AlbumsIndexImport
      parentRoute: typeof rootRoute
    }
    '/artists/': {
      id: '/artists/'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsIndexImport
      parentRoute: typeof rootRoute
    }
    '/playlist/': {
      id: '/playlist/'
      path: '/playlist'
      fullPath: '/playlist'
      preLoaderRoute: typeof PlaylistIndexImport
      parentRoute: typeof rootRoute
    }
    '/releases/': {
      id: '/releases/'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesIndexImport
      parentRoute: typeof rootRoute
    }
    '/signin/': {
      id: '/signin/'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninIndexImport
      parentRoute: typeof rootRoute
    }
    '/songs/': {
      id: '/songs/'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof SongsIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/edit/$albumId': {
      id: '/admin/edit/$albumId'
      path: '/admin/edit/$albumId'
      fullPath: '/admin/edit/$albumId'
      preLoaderRoute: typeof AdminEditAlbumIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/not-found': typeof NotFoundRoute
  '/signout': typeof SignoutRoute
  '/admin/add': typeof AdminAddRoute
  '/admin': typeof AdminIndexRoute
  '/albums': typeof AlbumsIndexRoute
  '/artists': typeof ArtistsIndexRoute
  '/playlist': typeof PlaylistIndexRoute
  '/releases': typeof ReleasesIndexRoute
  '/signin': typeof SigninIndexRoute
  '/songs': typeof SongsIndexRoute
  '/admin/edit/$albumId': typeof AdminEditAlbumIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/not-found': typeof NotFoundRoute
  '/signout': typeof SignoutRoute
  '/admin/add': typeof AdminAddRoute
  '/admin': typeof AdminIndexRoute
  '/albums': typeof AlbumsIndexRoute
  '/artists': typeof ArtistsIndexRoute
  '/playlist': typeof PlaylistIndexRoute
  '/releases': typeof ReleasesIndexRoute
  '/signin': typeof SigninIndexRoute
  '/songs': typeof SongsIndexRoute
  '/admin/edit/$albumId': typeof AdminEditAlbumIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/not-found': typeof NotFoundRoute
  '/signout': typeof SignoutRoute
  '/admin/add': typeof AdminAddRoute
  '/admin/': typeof AdminIndexRoute
  '/albums/': typeof AlbumsIndexRoute
  '/artists/': typeof ArtistsIndexRoute
  '/playlist/': typeof PlaylistIndexRoute
  '/releases/': typeof ReleasesIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/songs/': typeof SongsIndexRoute
  '/admin/edit/$albumId': typeof AdminEditAlbumIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/not-found'
    | '/signout'
    | '/admin/add'
    | '/admin'
    | '/albums'
    | '/artists'
    | '/playlist'
    | '/releases'
    | '/signin'
    | '/songs'
    | '/admin/edit/$albumId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/not-found'
    | '/signout'
    | '/admin/add'
    | '/admin'
    | '/albums'
    | '/artists'
    | '/playlist'
    | '/releases'
    | '/signin'
    | '/songs'
    | '/admin/edit/$albumId'
  id:
    | '__root__'
    | '/'
    | '/not-found'
    | '/signout'
    | '/admin/add'
    | '/admin/'
    | '/albums/'
    | '/artists/'
    | '/playlist/'
    | '/releases/'
    | '/signin/'
    | '/songs/'
    | '/admin/edit/$albumId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotFoundRoute: typeof NotFoundRoute
  SignoutRoute: typeof SignoutRoute
  AdminAddRoute: typeof AdminAddRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AlbumsIndexRoute: typeof AlbumsIndexRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
  PlaylistIndexRoute: typeof PlaylistIndexRoute
  ReleasesIndexRoute: typeof ReleasesIndexRoute
  SigninIndexRoute: typeof SigninIndexRoute
  SongsIndexRoute: typeof SongsIndexRoute
  AdminEditAlbumIdRoute: typeof AdminEditAlbumIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotFoundRoute: NotFoundRoute,
  SignoutRoute: SignoutRoute,
  AdminAddRoute: AdminAddRoute,
  AdminIndexRoute: AdminIndexRoute,
  AlbumsIndexRoute: AlbumsIndexRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
  PlaylistIndexRoute: PlaylistIndexRoute,
  ReleasesIndexRoute: ReleasesIndexRoute,
  SigninIndexRoute: SigninIndexRoute,
  SongsIndexRoute: SongsIndexRoute,
  AdminEditAlbumIdRoute: AdminEditAlbumIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/not-found",
        "/signout",
        "/admin/add",
        "/admin/",
        "/albums/",
        "/artists/",
        "/playlist/",
        "/releases/",
        "/signin/",
        "/songs/",
        "/admin/edit/$albumId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/not-found": {
      "filePath": "not-found.tsx"
    },
    "/signout": {
      "filePath": "signout.tsx"
    },
    "/admin/add": {
      "filePath": "admin/add.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.tsx"
    },
    "/albums/": {
      "filePath": "albums/index.tsx"
    },
    "/artists/": {
      "filePath": "artists/index.tsx"
    },
    "/playlist/": {
      "filePath": "playlist/index.tsx"
    },
    "/releases/": {
      "filePath": "releases/index.tsx"
    },
    "/signin/": {
      "filePath": "signin/index.tsx"
    },
    "/songs/": {
      "filePath": "songs/index.tsx"
    },
    "/admin/edit/$albumId": {
      "filePath": "admin/edit/$albumId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
